name: Render PlantUML to Wiki

on:
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Render PlantUML to wiki
        uses: frederikheld/render-plantuml-to-wiki-action@v1.0.1
        with:
          WIKI_TOKEN: ${{ secrets.WIKI_TOKEN }}
          INPUT_DIR: 'samples'
          OUTPUT_DIR: 'exports'
